server:
  port: 9000

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: "*"
  routes:
    DATARESTDEMOSERVICE:
      path: /person/**